### PR TITLE
Update OpenJPH

### LINKED ISSUE #3: Add option for TLM markers
Latest OpenJPH has support for adding TLM markers, updating the JS wrapper to allow setting that option would be great for DICOM use cases.

### LINKED ISSUE #4: Updating to latest OpenJPH breaks encoder
When updating the OpenJPH submodule to the latest commit, test encoding throws the following error:

```
RuntimeError: null function or function signature mismatch
    at wasm://wasm/000a9b56:wasm-function[46]:0x94c
    at wasm://wasm/000a9b56:wasm-function[54]:0x129f
    at wasm://wasm/000a9b56:wasm-function[72]:0x2c5c
    at wasm://wasm/000a9b56:wasm-function[159]:0xff13
    at invoke_iiii (/workspaces/openjphjs/dist/openjphjs.js:1:60705)
    at wasm://wasm/000a9b56:wasm-function[185]:0x14b24
    at wasm://wasm/000a9b56:wasm-function[109]:0x75c1
    at HTJ2KEncoder.HTJ2KEncoder$encode [as encode] (eval at new_ (/workspaces/openjphjs/dist/openjphjs.js:1:36933), <anonymous>:8:1)
    at encode (/workspaces/openjphjs/test/node/index.js:42:15)
    at openjphjs.onRuntimeInitialized (/workspaces/openjphjs/test/node/index.js:63:3)
```

### PR DESCRIPTION
**Pull request by jmhmd**
Support for TLM, SOT markers
Fixes #3
Fixes #4

### CODE REVIEW

**Comment by jmhmd** [comment]
I guess it doesn't really fix #3, this adds support for those markers from OpenJPH but doesn't expose the option in openjphjs

**Comment by jmhmd** [comment]
Now this does fix #3, exposing the wrapper functions to JS

**Comment by chafey** [comment]
Why did you add test/mode/test.js when the same code is already in index.js?

**Comment by chafey** [comment]
Please remove the build artifacts in /dist - I will build them on next release

**Comment by chafey** [comment]
the rest looks good - will merge when the issues above are resolved

**Comment by chafey** [comment]
Integrated via https://github.com/chafey/openjphjs/pull/8

**Comment by chafey** [comment]
Integrated via https://github.com/chafey/openjphjs/pull/8

**Pull request closed without merging**
